//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class M_DATA_PPMHP_WEBEntities : DbContext
    {
        public M_DATA_PPMHP_WEBEntities()
            : base("name=M_DATA_PPMHP_WEBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_Autori_Discipline> tbl_Autori_Discipline { get; set; }
        public DbSet<tbl_Autori_Grupe> tbl_Autori_Grupe { get; set; }
        public DbSet<tbl_Autori_povijest> tbl_Autori_povijest { get; set; }
        public DbSet<tbl_Autori_Pseudonimi> tbl_Autori_Pseudonimi { get; set; }
        public DbSet<tbl_Brojevi_predmeta> tbl_Brojevi_predmeta { get; set; }
        public DbSet<tbl_Def_Forme> tbl_Def_Forme { get; set; }
        public DbSet<tbl_Def_Izbornik> tbl_Def_Izbornik { get; set; }
        public DbSet<tbl_Def_Izbornik_SEK> tbl_Def_Izbornik_SEK { get; set; }
        public DbSet<tbl_Def_Jedinica_vremena> tbl_Def_Jedinica_vremena { get; set; }
        public DbSet<tbl_Def_Polja_Upiti_Extra> tbl_Def_Polja_Upiti_Extra { get; set; }
        public DbSet<tbl_Def_Struktura> tbl_Def_Struktura { get; set; }
        public DbSet<tbl_Def_Struktura_detalji> tbl_Def_Struktura_detalji { get; set; }
        public DbSet<tbl_Def_Struktura_iznimke> tbl_Def_Struktura_iznimke { get; set; }
        public DbSet<tbl_Def_Struktura_plus> tbl_Def_Struktura_plus { get; set; }
        public DbSet<tbl_Def_Struktura_upiti_refiners> tbl_Def_Struktura_upiti_refiners { get; set; }
        public DbSet<tbl_Def_Tipovi_knjiga> tbl_Def_Tipovi_knjiga { get; set; }
        public DbSet<tbl_Def_Vrijeme> tbl_Def_Vrijeme { get; set; }
        public DbSet<tbl_Inventarizacija> tbl_Inventarizacija { get; set; }
        public DbSet<tbl_Ispisi> tbl_Ispisi { get; set; }
        public DbSet<tbl_Ispisi_redci> tbl_Ispisi_redci { get; set; }
        public DbSet<tbl_Izlozbe_odrzavanja> tbl_Izlozbe_odrzavanja { get; set; }
        public DbSet<tbl_Izlozbe_organizatori> tbl_Izlozbe_organizatori { get; set; }
        public DbSet<tbl_Izrada> tbl_Izrada { get; set; }
        public DbSet<tbl_Kartica> tbl_Kartica { get; set; }
        public DbSet<tbl_Kataloska_jedinica> tbl_Kataloska_jedinica { get; set; }
        public DbSet<tbl_Kljucne_rijeci> tbl_Kljucne_rijeci { get; set; }
        public DbSet<tbl_Knjiga_ulaska> tbl_Knjiga_ulaska { get; set; }
        public DbSet<tbl_Knjiga_ulaska_Template> tbl_Knjiga_ulaska_Template { get; set; }
        public DbSet<tbl_KUL_brojevi> tbl_KUL_brojevi { get; set; }
        public DbSet<tbl_Log_Greske> tbl_Log_Greske { get; set; }
        public DbSet<tbl_Log_promjena_smjestaja> tbl_Log_promjena_smjestaja { get; set; }
        public DbSet<tbl_Media_collector> tbl_Media_collector { get; set; }
        public DbSet<tbl_Mjere> tbl_Mjere { get; set; }
        public DbSet<tbl_Nalaziste_datacija> tbl_Nalaziste_datacija { get; set; }
        public DbSet<tbl_Naslovi> tbl_Naslovi { get; set; }
        public DbSet<tbl_Natpisi_i_oznake> tbl_Natpisi_i_oznake { get; set; }
        public DbSet<tbl_Nazivi> tbl_Nazivi { get; set; }
        public DbSet<tbl_Nazivlje> tbl_Nazivlje { get; set; }
        public DbSet<tbl_Ocuvanost> tbl_Ocuvanost { get; set; }
        public DbSet<tbl_Operatori> tbl_Operatori { get; set; }
        public DbSet<tbl_Parametri_za_Ispisi_redci> tbl_Parametri_za_Ispisi_redci { get; set; }
        public DbSet<tbl_Parametri_za_korisnike> tbl_Parametri_za_korisnike { get; set; }
        public DbSet<tbl_Pod_Oznake> tbl_Pod_Oznake { get; set; }
        public DbSet<tbl_PopisParametara> tbl_PopisParametara { get; set; }
        public DbSet<tbl_Povijest_predmeta> tbl_Povijest_predmeta { get; set; }
        public DbSet<tbl_Predmeti_u_zbirkama> tbl_Predmeti_u_zbirkama { get; set; }
        public DbSet<tbl_Pripadnosti> tbl_Pripadnosti { get; set; }
        public DbSet<tbl_Reference> tbl_Reference { get; set; }
        public DbSet<tbl_Reprodukcijska_prava> tbl_Reprodukcijska_prava { get; set; }
        public DbSet<tbl_Sadrzaj> tbl_Sadrzaj { get; set; }
        public DbSet<tbl_Srodni_nazivi> tbl_Srodni_nazivi { get; set; }
        public DbSet<tbl_T_Autori> tbl_T_Autori { get; set; }
        public DbSet<tbl_T_Dijelovi> tbl_T_Dijelovi { get; set; }
        public DbSet<tbl_T_Dimenzije> tbl_T_Dimenzije { get; set; }
        public DbSet<tbl_T_Drzave> tbl_T_Drzave { get; set; }
        public DbSet<tbl_T_Izlozbe> tbl_T_Izlozbe { get; set; }
        public DbSet<tbl_T_Izlozbe_institucije> tbl_T_Izlozbe_institucije { get; set; }
        public DbSet<tbl_T_Izlozbe_organizatori> tbl_T_Izlozbe_organizatori { get; set; }
        public DbSet<tbl_T_Izvori_nabave> tbl_T_Izvori_nabave { get; set; }
        public DbSet<tbl_T_Jedinice_Mjere> tbl_T_Jedinice_Mjere { get; set; }
        public DbSet<tbl_T_Jezici> tbl_T_Jezici { get; set; }
        public DbSet<tbl_T_Kategorija_vrijednosti> tbl_T_Kategorija_vrijednosti { get; set; }
        public DbSet<tbl_T_Kljucne_rijeci> tbl_T_Kljucne_rijeci { get; set; }
        public DbSet<tbl_T_Kustosi> tbl_T_Kustosi { get; set; }
        public DbSet<tbl_T_Mape> tbl_T_Mape { get; set; }
        public DbSet<tbl_T_Materijali> tbl_T_Materijali { get; set; }
        public DbSet<tbl_T_Mjesta> tbl_T_Mjesta { get; set; }
        public DbSet<tbl_T_Mjesta_opis> tbl_T_Mjesta_opis { get; set; }
        public DbSet<tbl_T_Motivi> tbl_T_Motivi { get; set; }
        public DbSet<tbl_T_Nacini_prikupljanja> tbl_T_Nacini_prikupljanja { get; set; }
        public DbSet<tbl_T_Nalaziste> tbl_T_Nalaziste { get; set; }
        public DbSet<tbl_T_Nalaziste_vrsta> tbl_T_Nalaziste_vrsta { get; set; }
        public DbSet<tbl_T_Nazivi> tbl_T_Nazivi { get; set; }
        public DbSet<tbl_T_Nazivi_opis> tbl_T_Nazivi_opis { get; set; }
        public DbSet<tbl_T_Ocuvanosti> tbl_T_Ocuvanosti { get; set; }
        public DbSet<tbl_T_Ornamenti> tbl_T_Ornamenti { get; set; }
        public DbSet<tbl_T_Osobe_i_inst_odrednice> tbl_T_Osobe_i_inst_odrednice { get; set; }
        public DbSet<tbl_T_Osobe_i_institucije> tbl_T_Osobe_i_institucije { get; set; }
        public DbSet<tbl_T_Pojmovnik> tbl_T_Pojmovnik { get; set; }
        public DbSet<tbl_T_Povezanosti> tbl_T_Povezanosti { get; set; }
        public DbSet<tbl_T_Pribavljanje> tbl_T_Pribavljanje { get; set; }
        public DbSet<tbl_T_Pripadnosti> tbl_T_Pripadnosti { get; set; }
        public DbSet<tbl_T_Reference> tbl_T_Reference { get; set; }
        public DbSet<tbl_T_Reference_oblik> tbl_T_Reference_oblik { get; set; }
        public DbSet<tbl_T_Sadrzaj_predmet> tbl_T_Sadrzaj_predmet { get; set; }
        public DbSet<tbl_T_Sakupljaci> tbl_T_Sakupljaci { get; set; }
        public DbSet<tbl_T_Smjestaj> tbl_T_Smjestaj { get; set; }
        public DbSet<tbl_T_Smjestaj_privremeni> tbl_T_Smjestaj_privremeni { get; set; }
        public DbSet<tbl_T_Smjestaj_privremeni_vrsta> tbl_T_Smjestaj_privremeni_vrsta { get; set; }
        public DbSet<tbl_T_Smjestaj_stalni> tbl_T_Smjestaj_stalni { get; set; }
        public DbSet<tbl_T_Stupanj_dovrsenosti> tbl_T_Stupanj_dovrsenosti { get; set; }
        public DbSet<tbl_T_Tehnike> tbl_T_Tehnike { get; set; }
        public DbSet<tbl_T_Uloge_autora> tbl_T_Uloge_autora { get; set; }
        public DbSet<tbl_T_Uporabe> tbl_T_Uporabe { get; set; }
        public DbSet<tbl_T_Valute> tbl_T_Valute { get; set; }
        public DbSet<tbl_T_Virtualne_zbirke> tbl_T_Virtualne_zbirke { get; set; }
        public DbSet<tbl_T_Vremenske_odrednice> tbl_T_Vremenske_odrednice { get; set; }
        public DbSet<tbl_T_Vrste_brojeva> tbl_T_Vrste_brojeva { get; set; }
        public DbSet<tbl_T_Vrste_datoteka> tbl_T_Vrste_datoteka { get; set; }
        public DbSet<tbl_T_Vrste_naslova> tbl_T_Vrste_naslova { get; set; }
        public DbSet<tbl_T_Vrste_natpisa> tbl_T_Vrste_natpisa { get; set; }
        public DbSet<tbl_T_Vrste_naziva> tbl_T_Vrste_naziva { get; set; }
        public DbSet<tbl_T_Vrste_odgovornosti> tbl_T_Vrste_odgovornosti { get; set; }
        public DbSet<tbl_T_Vrste_organizacije_izlozbe> tbl_T_Vrste_organizacije_izlozbe { get; set; }
        public DbSet<tbl_T_Vrste_reference> tbl_T_Vrste_reference { get; set; }
        public DbSet<tbl_T_Vrste_sadrzaja> tbl_T_Vrste_sadrzaja { get; set; }
        public DbSet<tbl_T_Zbirke> tbl_T_Zbirke { get; set; }
        public DbSet<tbl_Teren_sezona> tbl_Teren_sezona { get; set; }
        public DbSet<tbl_U_Dijelovi_predmeta> tbl_U_Dijelovi_predmeta { get; set; }
        public DbSet<tbl_U_Materijali_u_dijelovima> tbl_U_Materijali_u_dijelovima { get; set; }
        public DbSet<tbl_U_Predmeti_na_izlozbama> tbl_U_Predmeti_na_izlozbama { get; set; }
        public DbSet<tbl_Update> tbl_Update { get; set; }
        public DbSet<tbl_Upiti> tbl_Upiti { get; set; }
        public DbSet<tbl_Upiti_redci> tbl_Upiti_redci { get; set; }
        public DbSet<tbl_Vrijednosti> tbl_Vrijednosti { get; set; }
        public DbSet<vw_Kartica> vw_Kartica { get; set; }
        public DbSet<vw_Stuff_ALL> vw_Stuff_ALL { get; set; }
        public DbSet<vw_T_Autori> vw_T_Autori { get; set; }
        public DbSet<vw_T_Izvori_nabave> vw_T_Izvori_nabave { get; set; }
        public DbSet<vw_T_Kustosi> vw_T_Kustosi { get; set; }
        public DbSet<vw_T_Osobe_i_inst_odrednice> vw_T_Osobe_i_inst_odrednice { get; set; }
        public DbSet<vw_T_Sakupljaci> vw_T_Sakupljaci { get; set; }
        public DbSet<vw_Web_Rezultati> vw_Web_Rezultati { get; set; }
        public DbSet<vw_Zbirke_prva_zadnja_zbroj> vw_Zbirke_prva_zadnja_zbroj { get; set; }
    
        public virtual ObjectResult<usp_Mjesta_DohvatiSve_Result> usp_Mjesta_DohvatiSve()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Mjesta_DohvatiSve_Result>("usp_Mjesta_DohvatiSve");
        }
    
        public virtual ObjectResult<usp_Zbirke_DohvatiSve_Result> usp_Zbirke_DohvatiSve()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Zbirke_DohvatiSve_Result>("usp_Zbirke_DohvatiSve");
        }
    
        public virtual ObjectResult<Nullable<int>> postaviIdentity(Nullable<int> idBroj, Nullable<int> idSubBroj)
        {
            var idBrojParameter = idBroj.HasValue ?
                new ObjectParameter("idBroj", idBroj) :
                new ObjectParameter("idBroj", typeof(int));
    
            var idSubBrojParameter = idSubBroj.HasValue ?
                new ObjectParameter("idSubBroj", idSubBroj) :
                new ObjectParameter("idSubBroj", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("postaviIdentity", idBrojParameter, idSubBrojParameter);
        }
    
        public virtual int testREK2(string tablica, string sifra, Nullable<int> iDT)
        {
            var tablicaParameter = tablica != null ?
                new ObjectParameter("tablica", tablica) :
                new ObjectParameter("tablica", typeof(string));
    
            var sifraParameter = sifra != null ?
                new ObjectParameter("sifra", sifra) :
                new ObjectParameter("sifra", typeof(string));
    
            var iDTParameter = iDT.HasValue ?
                new ObjectParameter("IDT", iDT) :
                new ObjectParameter("IDT", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("testREK2", tablicaParameter, sifraParameter, iDTParameter);
        }
    }
}
