//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Def_Tipovi_knjiga
    {
        public string Tip { get; set; }
        public Nullable<int> Zadnji_broj { get; set; }
        public string Naziv { get; set; }
        public int ID { get; set; }
    }
}
