//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Def_Polja_Upiti_Extra
    {
        public int ID { get; set; }
        public Nullable<int> poljeIDT { get; set; }
        public string @operator { get; set; }
        public string funkVrijednost { get; set; }
        public string fullString { get; set; }
        public string poljeIme { get; set; }
        public string tablica { get; set; }
        public string preString { get; set; }
        public string postString { get; set; }
        public int kojaVrijednost { get; set; }
        public string fullStringNE { get; set; }
    }
}
