//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_T_Mjesta_opis
    {
        public int Opis_Naziva_mjesta_ID { get; set; }
        public string Opis { get; set; }
        public Nullable<short> Razina { get; set; }
        public string Opis_engleski { get; set; }
        public bool Zasticeni_pojam { get; set; }
        public Nullable<int> Ucestalost { get; set; }
        public bool Nevidljiv { get; set; }
        public bool Odabir { get; set; }
        public string Odgovornost { get; set; }
        public string Reference { get; set; }
        public string Biljeske { get; set; }
        public Nullable<int> ID_Tablice { get; set; }
        public Nullable<int> ID_leksikon { get; set; }
        public Nullable<double> Sort { get; set; }
        public string Pojam2 { get; set; }
    }
}
