//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Def_Forme
    {
        public int ID { get; set; }
        public bool imaFokus { get; set; }
        public string title { get; set; }
        public string tmpl { get; set; }
        public string tablica { get; set; }
        public int odabrano { get; set; }
        public int recordCount { get; set; }
        public bool buttonBox { get; set; }
        public bool cont { get; set; }
    }
}
