//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Def_Struktura_iznimke
    {
        public int IDT { get; set; }
        public string Pojam { get; set; }
        public string Naziv { get; set; }
        public string Tip { get; set; }
        public string T_Tbl { get; set; }
        public string T_Sql { get; set; }
        public string Napomena { get; set; }
        public Nullable<int> Nad_IDT { get; set; }
        public Nullable<int> Preporuceni_IDT { get; set; }
        public int AutoBroj { get; set; }
        public Nullable<bool> Zasticeni_pojam { get; set; }
        public Nullable<int> Pozicija { get; set; }
        public string Opis { get; set; }
        public string DataType { get; set; }
        public string Duzina { get; set; }
        public Nullable<bool> PKey { get; set; }
        public string NNaziv_polja { get; set; }
        public string DefValue { get; set; }
        public string Tablica { get; set; }
        public Nullable<bool> Za_ucestalost { get; set; }
        public string Ispis_Param_1 { get; set; }
        public string Ispis_Param_2 { get; set; }
        public string Ispis_Param_3 { get; set; }
        public string Ispis_Param_4 { get; set; }
        public string Ispis_Param_5 { get; set; }
        public string Ispis_Param_6 { get; set; }
        public string Ispis_Param_7 { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<bool> Nevidljiv { get; set; }
        public Nullable<int> ID_Tablice { get; set; }
        public Nullable<int> Datum { get; set; }
    }
}
