//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Natpisi_i_oznake
    {
        public Nullable<int> ID_Broj { get; set; }
        public string NIO_Tekst { get; set; }
        public Nullable<int> NIO_IDT_Vrsta { get; set; }
        public string NIO_Opis { get; set; }
        public Nullable<int> NIO_IDT_Jezik { get; set; }
        public string NIO_Prijevod { get; set; }
        public Nullable<int> NIO_IDT_Smjestaj { get; set; }
        public Nullable<int> NIO_IDT_Tehnika { get; set; }
        public int ID { get; set; }
        public string NIO_Pismo { get; set; }
    
        public virtual tbl_Kartica tbl_Kartica { get; set; }
        public virtual tbl_T_Jezici tbl_T_Jezici { get; set; }
        public virtual tbl_T_Smjestaj tbl_T_Smjestaj { get; set; }
        public virtual tbl_T_Tehnike tbl_T_Tehnike { get; set; }
        public virtual tbl_T_Vrste_natpisa tbl_T_Vrste_natpisa { get; set; }
    }
}
