//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Predmeti_u_zbirkama
    {
        public int ID_Broj { get; set; }
        public int VZB_IDT_Virtualna_zbirka { get; set; }
        public Nullable<int> VZB_Vrsta_virtualne_zbirke { get; set; }
        public int ID { get; set; }
        public Nullable<int> kombo_polje { get; set; }
        public Nullable<double> Sort { get; set; }
        public Nullable<int> IDT_Smjestaj { get; set; }
        public string Napomena { get; set; }
    
        public virtual tbl_T_Smjestaj_privremeni tbl_T_Smjestaj_privremeni { get; set; }
    }
}
