//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Media_collector
    {
        public Nullable<int> ID_Slike { get; set; }
        public int ID_Broj { get; set; }
        public int ID_Sub_Broj { get; set; }
        public string MC_Staza_slike { get; set; }
        public Nullable<bool> MC_Identity { get; set; }
        public int AutoBroj { get; set; }
        public string MC_TMF { get; set; }
        public string MC_Tip { get; set; }
        public Nullable<bool> MC_rv { get; set; }
        public Nullable<bool> MC_Web { get; set; }
        public string MC_Tekst { get; set; }
        public string MC_Naslov { get; set; }
        public string MC_Tekst2 { get; set; }
        public bool MC_CB { get; set; }
    
        public virtual tbl_Kartica tbl_Kartica { get; set; }
    }
}
