//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Parametri_za_korisnike
    {
        public string Institucija_ID { get; set; }
        public string Korisnik_UserName { get; set; }
        public string Parametar { get; set; }
        public string Vrijednost { get; set; }
        public Nullable<int> ID_Broj { get; set; }
        public int ID { get; set; }
    }
}
