//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Def_Vrijeme
    {
        public string DFV_Opis { get; set; }
        public string DFV_St_od { get; set; }
        public string DFV_St_do { get; set; }
        public string DFV_G_od { get; set; }
        public string DFV_G_do { get; set; }
        public Nullable<bool> DFV_St_plus { get; set; }
        public string DFV_Mj_od { get; set; }
        public string DFV_Mj_do { get; set; }
        public Nullable<bool> Vidljiv { get; set; }
    }
}
