//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_KUL_brojevi
    {
        public Nullable<int> KUL_TEMPL_ID { get; set; }
        public Nullable<int> ID_Broj_IZ { get; set; }
        public Nullable<int> ID_Broj_U { get; set; }
        public string Inv_broj_IZ { get; set; }
        public string Inv_broj_U { get; set; }
        public Nullable<System.DateTime> datum { get; set; }
        public Nullable<int> sort { get; set; }
        public int ID { get; set; }
    
        public virtual tbl_Knjiga_ulaska_Template tbl_Knjiga_ulaska_Template { get; set; }
    }
}
