//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Autori_Pseudonimi
    {
        public Nullable<int> ID_Autor { get; set; }
        public Nullable<int> ID_Pseudonim { get; set; }
        public int ID { get; set; }
    
        public virtual tbl_T_Autori tbl_T_Autori { get; set; }
        public virtual tbl_T_Autori tbl_T_Autori1 { get; set; }
    }
}
