//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Operatori
    {
        public string Operator { get; set; }
        public string Naziv_operatora { get; set; }
        public string Vrsta { get; set; }
        public Nullable<int> podvrsta { get; set; }
    }
}
