//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Brojevi_predmeta
    {
        public Nullable<int> ID_Broj { get; set; }
        public string BRP_Broj { get; set; }
        public Nullable<int> BRP_IDT_Vrsta { get; set; }
        public string BRP_Datum { get; set; }
        public int ID { get; set; }
        public Nullable<int> BRP_Datum_SORT { get; set; }
    
        public virtual tbl_T_Vrste_brojeva tbl_T_Vrste_brojeva { get; set; }
        public virtual tbl_Kartica tbl_Kartica { get; set; }
    }
}
