//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Mjere
    {
        public Nullable<int> ID_Broj { get; set; }
        public Nullable<int> MJR_IDT_Mjereni_dio { get; set; }
        public Nullable<float> MJR_Mjera { get; set; }
        public Nullable<int> MJR_IDT_Dimenzija { get; set; }
        public Nullable<int> MJR_IDT_Jedinica_mjere { get; set; }
        public int ID { get; set; }
        public Nullable<float> Sort_polje { get; set; }
        public Nullable<int> MJR_IDT_Mjereni_dio2 { get; set; }
    
        public virtual tbl_Kartica tbl_Kartica { get; set; }
        public virtual tbl_T_Dimenzije tbl_T_Dimenzije { get; set; }
        public virtual tbl_T_Jedinice_Mjere tbl_T_Jedinice_Mjere { get; set; }
        public virtual tbl_T_Dijelovi tbl_T_Dijelovi { get; set; }
    }
}
