//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_T_Mjesta
    {
        public tbl_T_Mjesta()
        {
            this.tbl_Izlozbe_odrzavanja = new HashSet<tbl_Izlozbe_odrzavanja>();
            this.tbl_Izrada = new HashSet<tbl_Izrada>();
            this.tbl_Povijest_predmeta = new HashSet<tbl_Povijest_predmeta>();
            this.tbl_T_Autori = new HashSet<tbl_T_Autori>();
            this.tbl_T_Autori1 = new HashSet<tbl_T_Autori>();
            this.tbl_T_Autori2 = new HashSet<tbl_T_Autori>();
        }
    
        public int IDT { get; set; }
        public string Pojam { get; set; }
        public Nullable<int> Nad_IDT { get; set; }
        public Nullable<int> Preporuceni_IDT { get; set; }
        public string Napomena { get; set; }
        public Nullable<int> Stari_ID { get; set; }
        public string PozivniBroj { get; set; }
        public string BrojZupanije { get; set; }
        public Nullable<int> RedniBrojZupanije { get; set; }
        public Nullable<bool> Status_grada { get; set; }
        public Nullable<bool> Status_općine { get; set; }
        public Nullable<int> ZupanijaID { get; set; }
        public Nullable<int> BrojPoste { get; set; }
        public Nullable<int> OpcinaID { get; set; }
        public Nullable<int> Opis_ID { get; set; }
        public int AutoBroj { get; set; }
        public Nullable<bool> Zasticeni_pojam { get; set; }
        public Nullable<int> Ucestalost { get; set; }
        public Nullable<bool> Nevidljiv { get; set; }
        public Nullable<bool> Odabir { get; set; }
        public string Odgovornost { get; set; }
        public string Reference { get; set; }
        public string Biljeske { get; set; }
        public Nullable<int> ID_Tablice { get; set; }
        public Nullable<int> ID_leksikon { get; set; }
        public Nullable<double> Sort { get; set; }
        public string Pojam2 { get; set; }
        public Nullable<int> HijerarhijaVrsta { get; set; }
        public Nullable<int> statusPotvrde { get; set; }
    
        public virtual ICollection<tbl_Izlozbe_odrzavanja> tbl_Izlozbe_odrzavanja { get; set; }
        public virtual ICollection<tbl_Izrada> tbl_Izrada { get; set; }
        public virtual ICollection<tbl_Povijest_predmeta> tbl_Povijest_predmeta { get; set; }
        public virtual ICollection<tbl_T_Autori> tbl_T_Autori { get; set; }
        public virtual ICollection<tbl_T_Autori> tbl_T_Autori1 { get; set; }
        public virtual ICollection<tbl_T_Autori> tbl_T_Autori2 { get; set; }
    }
}
