//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_U_Predmeti_na_izlozbama
    {
        public Nullable<int> ID_Broj { get; set; }
        public Nullable<int> PNI_IDT_Izlozbe { get; set; }
        public int ID { get; set; }
    
        public virtual tbl_Kartica tbl_Kartica { get; set; }
        public virtual tbl_T_Izlozbe tbl_T_Izlozbe { get; set; }
    }
}
