//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Nazivi
    {
        public Nullable<int> ID_Broj { get; set; }
        public Nullable<int> NAZ_IDT_Naziv_predmeta { get; set; }
        public Nullable<int> NAZ_IDT_Vrsta_naziva { get; set; }
        public string NAZ_Odgovornost { get; set; }
        public int ID { get; set; }
    
        public virtual tbl_Kartica tbl_Kartica { get; set; }
        public virtual tbl_T_Nazivi tbl_T_Nazivi { get; set; }
        public virtual tbl_T_Vrste_naziva tbl_T_Vrste_naziva { get; set; }
    }
}
