//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Reprodukcijska_prava
    {
        public string REP_Napomena { get; set; }
        public string REP_Vlasnik { get; set; }
        public string REP_Inv_br { get; set; }
        public Nullable<int> ID_Broj { get; set; }
        public int ID { get; set; }
    }
}
