//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Povijest_predmeta
    {
        public Nullable<int> ID_Broj { get; set; }
        public Nullable<int> POV_IDT_Mjesto { get; set; }
        public Nullable<int> POV_ID_Osoba_institucija { get; set; }
        public Nullable<int> POV_IDT_Vrsta_povezanosti { get; set; }
        public Nullable<int> POV_IDT_Uporaba { get; set; }
        public string POV_Vrijeme_opis { get; set; }
        public string POV_Vrijeme_vrijednost { get; set; }
        public string POV_Vrijeme_jedinica { get; set; }
        public Nullable<int> POV_Vrijeme_od { get; set; }
        public Nullable<int> POV_Vrijeme_do { get; set; }
        public string POV_Vrijeme_opis2 { get; set; }
        public string POV_Vrijeme_vrijednost2 { get; set; }
        public string POV_Vrijeme_jedinica2 { get; set; }
        public Nullable<bool> POV_Period { get; set; }
        public Nullable<bool> POV_Period_do { get; set; }
        public string POV_Napomena { get; set; }
        public int ID { get; set; }
    
        public virtual tbl_Kartica tbl_Kartica { get; set; }
        public virtual tbl_T_Osobe_i_institucije tbl_T_Osobe_i_institucije { get; set; }
        public virtual tbl_T_Mjesta tbl_T_Mjesta { get; set; }
        public virtual tbl_T_Uporabe tbl_T_Uporabe { get; set; }
        public virtual tbl_T_Povezanosti tbl_T_Povezanosti { get; set; }
    }
}
