//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Teren_sezona
    {
        public int IDT { get; set; }
        public Nullable<int> IDT_Nalaziste { get; set; }
        public Nullable<int> IDT_Voditelj { get; set; }
        public string Datum_od { get; set; }
        public string Datum_do { get; set; }
        public string Napomena { get; set; }
        public string Pojam2 { get; set; }
    }
}
