//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Upiti_redci
    {
        public string Naziv { get; set; }
        public string Opis { get; set; }
        public string Zagrada_otvorena_1 { get; set; }
        public Nullable<int> ID_Polje_1 { get; set; }
        public string Polje_1 { get; set; }
        public string Operator_1 { get; set; }
        public string Vrijednost_1 { get; set; }
        public string Zagrada_zatvorena_1 { get; set; }
        public string Operator_redka_1 { get; set; }
        public string Tablica_1 { get; set; }
        public string TermTablica_1 { get; set; }
        public Nullable<int> Vrijeme_od_1 { get; set; }
        public Nullable<int> Vrijeme_do_1 { get; set; }
        public Nullable<bool> BezTez_1 { get; set; }
        public string Zagrada_otvorena_2 { get; set; }
        public Nullable<int> ID_Polje_2 { get; set; }
        public string Polje_2 { get; set; }
        public string Operator_2 { get; set; }
        public string Vrijednost_2 { get; set; }
        public string Zagrada_zatvorena_2 { get; set; }
        public string Operator_redka_2 { get; set; }
        public string Tablica_2 { get; set; }
        public string TermTablica_2 { get; set; }
        public Nullable<int> Vrijeme_od_2 { get; set; }
        public Nullable<int> Vrijeme_do_2 { get; set; }
        public Nullable<bool> BezTez_2 { get; set; }
        public string Zagrada_otvorena_3 { get; set; }
        public Nullable<int> ID_Polje_3 { get; set; }
        public string Polje_3 { get; set; }
        public string Operator_3 { get; set; }
        public string Vrijednost_3 { get; set; }
        public string Zagrada_zatvorena_3 { get; set; }
        public string Operator_redka_3 { get; set; }
        public string Tablica_3 { get; set; }
        public string TermTablica_3 { get; set; }
        public Nullable<int> Vrijeme_od_3 { get; set; }
        public Nullable<int> Vrijeme_do_3 { get; set; }
        public Nullable<bool> BezTez_3 { get; set; }
        public string Zagrada_otvorena_4 { get; set; }
        public Nullable<int> ID_Polje_4 { get; set; }
        public string Polje_4 { get; set; }
        public string Operator_4 { get; set; }
        public string Vrijednost_4 { get; set; }
        public string Zagrada_zatvorena_4 { get; set; }
        public string Operator_redka_4 { get; set; }
        public string Tablica_4 { get; set; }
        public string TermTablica_4 { get; set; }
        public Nullable<int> Vrijeme_od_4 { get; set; }
        public Nullable<int> Vrijeme_do_4 { get; set; }
        public Nullable<bool> BezTez_4 { get; set; }
        public string Zagrada_otvorena_5 { get; set; }
        public Nullable<int> ID_Polje_5 { get; set; }
        public string Polje_5 { get; set; }
        public string Operator_5 { get; set; }
        public string Vrijednost_5 { get; set; }
        public string Zagrada_zatvorena_5 { get; set; }
        public string Operator_redka_5 { get; set; }
        public string Tablica_5 { get; set; }
        public string TermTablica_5 { get; set; }
        public Nullable<int> Vrijeme_od_5 { get; set; }
        public Nullable<int> Vrijeme_do_5 { get; set; }
        public Nullable<bool> BezTez_5 { get; set; }
        public string Zagrada_otvorena_6 { get; set; }
        public Nullable<int> ID_Polje_6 { get; set; }
        public string Polje_6 { get; set; }
        public string Operator_6 { get; set; }
        public string Vrijednost_6 { get; set; }
        public string Zagrada_zatvorena_6 { get; set; }
        public string Operator_redka_6 { get; set; }
        public string Tablica_6 { get; set; }
        public string TermTablica_6 { get; set; }
        public Nullable<int> Vrijeme_od_6 { get; set; }
        public Nullable<int> Vrijeme_do_6 { get; set; }
        public Nullable<bool> BezTez_6 { get; set; }
        public string Zagrada_otvorena_7 { get; set; }
        public Nullable<int> ID_Polje_7 { get; set; }
        public string Polje_7 { get; set; }
        public string Operator_7 { get; set; }
        public string Vrijednost_7 { get; set; }
        public string Zagrada_zatvorena_7 { get; set; }
        public string Operator_redka_7 { get; set; }
        public string Tablica_7 { get; set; }
        public string TermTablica_7 { get; set; }
        public Nullable<int> Vrijeme_od_7 { get; set; }
        public Nullable<int> Vrijeme_do_7 { get; set; }
        public Nullable<bool> BezTez_7 { get; set; }
        public Nullable<int> ID_Redka { get; set; }
        public Nullable<int> ID_Upita { get; set; }
        public int ID { get; set; }
    
        public virtual tbl_Upiti tbl_Upiti { get; set; }
    }
}
