//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Izlozbe_odrzavanja
    {
        public Nullable<int> IDT_Izlozbe { get; set; }
        public Nullable<int> ID_IZL_institucija { get; set; }
        public Nullable<int> IDT_IZL_mjesto { get; set; }
        public Nullable<int> IDT_IZL_drzava { get; set; }
        public string IZL_termin_od { get; set; }
        public string IZL_termin_do { get; set; }
        public int ID { get; set; }
    
        public virtual tbl_T_Izlozbe_institucije tbl_T_Izlozbe_institucije { get; set; }
        public virtual tbl_T_Drzave tbl_T_Drzave { get; set; }
        public virtual tbl_T_Mjesta tbl_T_Mjesta { get; set; }
        public virtual tbl_T_Izlozbe tbl_T_Izlozbe { get; set; }
    }
}
