//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Naslovi
    {
        public string NSL_Naslov { get; set; }
        public Nullable<int> NSL_IDT_Vrsta_naslova { get; set; }
        public string NSL_Prijevod_naslova { get; set; }
        public Nullable<int> NSL_IDT_Jezik_naslova { get; set; }
        public Nullable<int> ID_Broj { get; set; }
        public int ID { get; set; }
        public Nullable<float> Sort_polje { get; set; }
    
        public virtual tbl_Kartica tbl_Kartica { get; set; }
        public virtual tbl_T_Jezici tbl_T_Jezici { get; set; }
        public virtual tbl_T_Vrste_naslova tbl_T_Vrste_naslova { get; set; }
    }
}
