//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Kataloska_jedinica
    {
        public int ID_Broj { get; set; }
        public string k1 { get; set; }
        public Nullable<int> K1_Vrsta_ispisa { get; set; }
        public string k2 { get; set; }
        public Nullable<int> K2_Vrsta_ispisa { get; set; }
        public string k3 { get; set; }
        public Nullable<int> K3_Vrsta_ispisa { get; set; }
        public Nullable<int> KRT_Dirty { get; set; }
        public int ID { get; set; }
        public string k { get; set; }
        public string o { get; set; }
        public string o2 { get; set; }
        public string Legenda { get; set; }
        public string Legenda2 { get; set; }
        public string RTFField { get; set; }
        public string InvBr { get; set; }
        public bool k_zakljucano { get; set; }
        public bool k1_zakljucano { get; set; }
        public bool k2_zakljucano { get; set; }
        public bool k3_zakljucano { get; set; }
        public Nullable<int> k_Vrsta_ispisa { get; set; }
        public byte[] k1_OLE { get; set; }
        public string Dokument { get; set; }
        public Nullable<double> sort { get; set; }
    
        public virtual tbl_Kartica tbl_Kartica { get; set; }
    }
}
