//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Reference
    {
        public Nullable<int> ID_Broj { get; set; }
        public Nullable<int> ID_Reference { get; set; }
        public Nullable<int> REF_IDT_Vrsta_reference { get; set; }
        public string REF_Napomena { get; set; }
        public string REF_Param { get; set; }
        public Nullable<int> REF_IDT_Oblik_reference { get; set; }
        public string REF_Dodatni_podaci { get; set; }
        public string REF_Opis { get; set; }
        public int ID { get; set; }
        public Nullable<float> SORT_polje { get; set; }
    
        public virtual tbl_Kartica tbl_Kartica { get; set; }
        public virtual tbl_T_Reference_oblik tbl_T_Reference_oblik { get; set; }
        public virtual tbl_T_Vrste_reference tbl_T_Vrste_reference { get; set; }
    }
}
