//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Izlozbe_organizatori
    {
        public Nullable<int> IDT_Izlozbe { get; set; }
        public Nullable<int> IDT_IZL_vrsta_org { get; set; }
        public Nullable<int> ID_IZL_organizator { get; set; }
        public int ID { get; set; }
    
        public virtual tbl_T_Izlozbe_organizatori tbl_T_Izlozbe_organizatori { get; set; }
        public virtual tbl_T_Vrste_organizacije_izlozbe tbl_T_Vrste_organizacije_izlozbe { get; set; }
        public virtual tbl_T_Izlozbe tbl_T_Izlozbe { get; set; }
    }
}
