//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Pod_Oznake
    {
        public int ID_Broj { get; set; }
        public int ID_Broj_dijela { get; set; }
        public string Naslov { get; set; }
        public Nullable<int> Broj_Komada { get; set; }
        public Nullable<int> Broj_Dijelova { get; set; }
        public int ID { get; set; }
    }
}
