//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Autori_povijest
    {
        public Nullable<int> ID_Autora { get; set; }
        public Nullable<int> AUT_IDT_Mjesto { get; set; }
        public Nullable<int> AUT_ID_Osoba_institucija { get; set; }
        public Nullable<int> AUT_IDT_Vrsta_povezanosti { get; set; }
        public Nullable<int> AUT_IDT_Uporaba { get; set; }
        public string AUT_Vrijeme_opis { get; set; }
        public string AUT_Vrijeme_vrijednost { get; set; }
        public string AUT_Vrijeme_jedinica { get; set; }
        public Nullable<int> AUT_Vrijeme_od { get; set; }
        public Nullable<int> AUT_Vrijeme_do { get; set; }
        public string AUT_Vrijeme_opis2 { get; set; }
        public string AUT_Vrijeme_vrijednost2 { get; set; }
        public string AUT_Vrijeme_jedinica2 { get; set; }
        public Nullable<bool> AUT_Period { get; set; }
        public Nullable<bool> AUT_Period_do { get; set; }
        public int ID { get; set; }
    }
}
