//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Ispisi_redci
    {
        public Nullable<int> IDT { get; set; }
        public int Broj_redka { get; set; }
        public string Prefiks { get; set; }
        public Nullable<int> ID_Polje { get; set; }
        public string Sufiks { get; set; }
        public string FontName { get; set; }
        public Nullable<int> FontSize { get; set; }
        public Nullable<bool> Bold { get; set; }
        public Nullable<bool> Italic { get; set; }
        public Nullable<bool> Underline { get; set; }
        public Nullable<bool> Strikethru { get; set; }
        public Nullable<bool> CR { get; set; }
        public string Tablica { get; set; }
        public string TermTablica { get; set; }
        public string NazivPolja { get; set; }
        public Nullable<int> Nad_IDT { get; set; }
        public string Kategorija { get; set; }
        public Nullable<float> red { get; set; }
    }
}
