//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_U_Materijali_u_dijelovima
    {
        public int ID_Broj { get; set; }
        public int U_IDT_Dio_predmeta { get; set; }
        public int U_IDT_Materijal { get; set; }
        public int U_IDT_Tehnika { get; set; }
        public int ID { get; set; }
    
        public virtual tbl_Kartica tbl_Kartica { get; set; }
        public virtual tbl_T_Dijelovi tbl_T_Dijelovi { get; set; }
        public virtual tbl_T_Materijali tbl_T_Materijali { get; set; }
        public virtual tbl_T_Tehnike tbl_T_Tehnike { get; set; }
    }
}
