//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Def_Struktura_detalji
    {
        public Nullable<int> IDT { get; set; }
        public string Tip { get; set; }
        public string Parametar { get; set; }
        public string Default_vrijednost { get; set; }
        public int AutoBroj { get; set; }
    }
}
