//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Def_Struktura_upiti_refiners
    {
        public int IDT { get; set; }
        public string Pojam { get; set; }
        public string Naziv { get; set; }
        public string T_Tbl { get; set; }
        public string Napomena { get; set; }
        public string Tablica { get; set; }
        public string filter { get; set; }
        public string template { get; set; }
        public string title { get; set; }
        public bool refiner { get; set; }
        public string ID_Broj_polje { get; set; }
        public string ime { get; set; }
        public string dIme { get; set; }
        public Nullable<int> refinerSort { get; set; }
    }
}
