//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_T_Vrste_datoteka
    {
        public string ID_VRSTA { get; set; }
        public string Naziv { get; set; }
        public string filter { get; set; }
        public string staza_programa { get; set; }
        public string zamjenska_slika { get; set; }
    }
}
