//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Srodni_nazivi
    {
        public int ID { get; set; }
        public Nullable<int> ID_Tablice { get; set; }
        public Nullable<int> IDT_Naziv { get; set; }
        public Nullable<int> ID_Srodna_tablica { get; set; }
        public Nullable<int> IDT_Srodni_naziv { get; set; }
    }
}
