//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Sadrzaj
    {
        public int ID { get; set; }
        public Nullable<int> ID_Broj { get; set; }
        public Nullable<int> SDR_IDT_Predmet { get; set; }
        public string SDR_Opis { get; set; }
        public Nullable<int> SDR_IDT_Vrsta { get; set; }
        public Nullable<double> Sort_Polje { get; set; }
        public Nullable<int> SDR_Grupa { get; set; }
    
        public virtual tbl_Kartica tbl_Kartica { get; set; }
    }
}
