//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Log_promjena_smjestaja
    {
        public int ID { get; set; }
        public Nullable<int> ID_Broj { get; set; }
        public string Polje { get; set; }
        public string Pojam_prije { get; set; }
        public Nullable<int> IDT_prije { get; set; }
        public string Pojam_poslije { get; set; }
        public Nullable<int> IDT_poslije { get; set; }
        public Nullable<int> Promijenio_ID { get; set; }
        public string Promijenio_username { get; set; }
        public string Datum_promjene { get; set; }
        public string Napomena { get; set; }
    }
}
