//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Nazivlje
    {
        public int ID { get; set; }
        public string level_1 { get; set; }
        public string level_2 { get; set; }
        public string level_3 { get; set; }
        public string level_4 { get; set; }
        public string level_5 { get; set; }
        public string level_6 { get; set; }
        public string level_7 { get; set; }
        public string level_8 { get; set; }
        public string level_9 { get; set; }
        public string level_10 { get; set; }
        public string level_11 { get; set; }
        public string level_12 { get; set; }
    }
}
