//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Kartica
    {
        public tbl_Kartica()
        {
            this.tbl_Brojevi_predmeta = new HashSet<tbl_Brojevi_predmeta>();
            this.tbl_Inventarizacija = new HashSet<tbl_Inventarizacija>();
            this.tbl_Izrada = new HashSet<tbl_Izrada>();
            this.tbl_Kljucne_rijeci = new HashSet<tbl_Kljucne_rijeci>();
            this.tbl_Knjiga_ulaska = new HashSet<tbl_Knjiga_ulaska>();
            this.tbl_Media_collector = new HashSet<tbl_Media_collector>();
            this.tbl_Mjere = new HashSet<tbl_Mjere>();
            this.tbl_Naslovi = new HashSet<tbl_Naslovi>();
            this.tbl_Natpisi_i_oznake = new HashSet<tbl_Natpisi_i_oznake>();
            this.tbl_Nazivi = new HashSet<tbl_Nazivi>();
            this.tbl_Ocuvanost = new HashSet<tbl_Ocuvanost>();
            this.tbl_Povijest_predmeta = new HashSet<tbl_Povijest_predmeta>();
            this.tbl_Pripadnosti = new HashSet<tbl_Pripadnosti>();
            this.tbl_Reference = new HashSet<tbl_Reference>();
            this.tbl_Sadrzaj = new HashSet<tbl_Sadrzaj>();
            this.tbl_U_Dijelovi_predmeta = new HashSet<tbl_U_Dijelovi_predmeta>();
            this.tbl_U_Materijali_u_dijelovima = new HashSet<tbl_U_Materijali_u_dijelovima>();
            this.tbl_U_Predmeti_na_izlozbama = new HashSet<tbl_U_Predmeti_na_izlozbama>();
            this.tbl_Vrijednosti = new HashSet<tbl_Vrijednosti>();
        }
    
        public int ID_Broj { get; set; }
        public Nullable<int> KRT_IDT_Zbirka { get; set; }
        public string KRT_Inventarni_broj { get; set; }
        public string KRT_SORT_Inv_br { get; set; }
        public string KRT_Nabava_Broj_spisa { get; set; }
        public string KRT_Nabava_Napomena { get; set; }
        public string KRT_Nabava_datum { get; set; }
        public Nullable<float> KRT_Nabava_cijena { get; set; }
        public Nullable<int> KRT_IDT_Nabava_oblik { get; set; }
        public Nullable<int> KRT_ID_Nabava_Izvor { get; set; }
        public Nullable<int> KRT_IDT_Nabava_valuta { get; set; }
        public string KRT_Opis_Fizicki_opis { get; set; }
        public string KRT_Opis_Status_vrste { get; set; }
        public string KRT_Prikupljanje_Datum { get; set; }
        public Nullable<int> KRT_ID_Prikupljanje_Sakupljac { get; set; }
        public Nullable<int> KRT_IDT_Prikupljanje_Nacin { get; set; }
        public Nullable<int> KRT_IDT_Prikupljanje_Nalaziste { get; set; }
        public Nullable<int> KRT_IDT_Smjestaj_Stalni { get; set; }
        public Nullable<int> KRT_IDT_Smjestaj_Privremeni { get; set; }
        public Nullable<int> KRT_IDT_Smjestaj_Privremeni_vrsta { get; set; }
        public string KRT_Smjestaj_privremeni_datum { get; set; }
        public Nullable<int> KRT_ID_Inventirao { get; set; }
        public string KRT_Datum_inventiranja { get; set; }
        public string KRT_Napomena { get; set; }
        public string KRT_Inventarni_omot { get; set; }
        public string KRT_Kategorija_vrijednosti { get; set; }
        public Nullable<short> KRT_Broj_komada { get; set; }
        public Nullable<float> KRT_Broj_dijelova { get; set; }
        public string KRT_Broj_dijelova_Opis { get; set; }
        public string KRT_Otpis_Datum { get; set; }
        public string KRT_OTP_Datum_izlaza { get; set; }
        public string KRT_OTP_Način_izlaza { get; set; }
        public string KRT_OTP_Primatelj { get; set; }
        public string KRT_Institucija_Ime { get; set; }
        public string KRT_Institucija_Odjel { get; set; }
        public string KRT_Institucija_Adresa { get; set; }
        public string KRT_Institucija_Zemlja { get; set; }
        public string KRT_Ulaz_Sadasnji_vlasnik { get; set; }
        public string KRT_Ulaz_Depozitor { get; set; }
        public string KRT_Ulaz_Datum { get; set; }
        public string KRT_Ulaz_Broj { get; set; }
        public string KRT_Ulaz_Razlog { get; set; }
        public string Ornament { get; set; }
        public string KRT_Staza_identifikacijske_slike { get; set; }
        public Nullable<System.DateTime> C_Datum_unosa { get; set; }
        public int AutoBroj { get; set; }
        public string KRT_SD { get; set; }
        public Nullable<float> KRT_Iznos { get; set; }
        public Nullable<int> KRT_IDT_Valuta_iznos { get; set; }
        public string KRT_Datum_procjena { get; set; }
        public string KRT_Prikupljanje_Polozaj { get; set; }
        public string KRT_Prikupljanje_Koordinate { get; set; }
        public string KRT_Prikupljanje_Sonda_Blok { get; set; }
        public string KRT_Prikupljanje_Kvadrant { get; set; }
        public string KRT_Prikupljanje_Dubina { get; set; }
        public string KRT_Prikupljanje_Stratigrafska_jedinica { get; set; }
        public string KRT_Prikupljanje_Opis { get; set; }
        public string KRT_Prikupljanje_Okolnosti { get; set; }
        public string KRT_Opisni_MiT { get; set; }
        public Nullable<int> C_Def_Ispisa { get; set; }
        public Nullable<int> C_Def_Ispisa_Gl_obrazac { get; set; }
        public Nullable<int> KRT_IDT_Nabava_mjesto { get; set; }
        public bool KRT_Dirty { get; set; }
        public string KRT_Prikupljanje_Grob { get; set; }
        public bool Web { get; set; }
        public string KRT_Prikupljanje_datum_kraj { get; set; }
        public bool KRT_Samo_logicki { get; set; }
        public Nullable<int> KRT_Razina_dijelova_niza { get; set; }
        public Nullable<double> KRT_Prikupljanje_Koordinata_X { get; set; }
        public Nullable<double> KRT_Prikupljanje_Koordinata_Y { get; set; }
        public Nullable<double> KRT_Prikupljanje_Koordinata_Z { get; set; }
        public string KRT_Sifra_uzorka { get; set; }
        public string KRT_Spol { get; set; }
        public string KRT_Razvojni_stadij { get; set; }
        public bool KRT_B_Broji_komponente { get; set; }
        public string KRT_Za_pretrazivanjeS { get; set; }
        public Nullable<int> spoj_id_broj { get; set; }
        public string KRT_Opisne_mjere { get; set; }
        public bool KRT_Musko { get; set; }
        public bool KRT_Zensko { get; set; }
        public bool KRT_Djecje { get; set; }
        public Nullable<int> KRT_IDT_KEY_Lokalitet { get; set; }
        public Nullable<int> KRT_ID_Institucija { get; set; }
        public Nullable<int> KRT_IDT_Mapa { get; set; }
        public bool WEB_HVM { get; set; }
        public Nullable<int> KRT_Nabava_Datum_SORT { get; set; }
        public string KRT_Prikupljanje_sloj { get; set; }
        public string KRT_Prikupljanje_horizont { get; set; }
        public string KRT_Prikupljanje_sektor { get; set; }
        public string KRT_Prikupljanje_kutija { get; set; }
        public string KRT_Prikupljanje_boja { get; set; }
        public string KRT_Prikupljanje_faktura { get; set; }
        public string KRT_Prikupljanje_povrsina { get; set; }
        public bool KRT_Registracija { get; set; }
        public string KRT_Registracija_Datum { get; set; }
        public Nullable<int> KRT_Registracija_Datum_SORT { get; set; }
        public Nullable<int> KRT_Dio_od { get; set; }
        public bool KRT_Ubrojivo { get; set; }
        public Nullable<decimal> sort_web { get; set; }
        public bool DCA_Online { get; set; }
        public string KRT_InvBroj_Prefix { get; set; }
        public Nullable<int> KRT_InvBroj_Broj { get; set; }
        public string KRT_InvBroj_Ostatak { get; set; }
        public Nullable<int> KRT_IDT_Prikupljanje_Nalaziste_sezona { get; set; }
    
        public virtual ICollection<tbl_Brojevi_predmeta> tbl_Brojevi_predmeta { get; set; }
        public virtual ICollection<tbl_Inventarizacija> tbl_Inventarizacija { get; set; }
        public virtual ICollection<tbl_Izrada> tbl_Izrada { get; set; }
        public virtual tbl_T_Sakupljaci tbl_T_Sakupljaci { get; set; }
        public virtual tbl_Kataloska_jedinica tbl_Kataloska_jedinica { get; set; }
        public virtual ICollection<tbl_Kljucne_rijeci> tbl_Kljucne_rijeci { get; set; }
        public virtual ICollection<tbl_Knjiga_ulaska> tbl_Knjiga_ulaska { get; set; }
        public virtual ICollection<tbl_Media_collector> tbl_Media_collector { get; set; }
        public virtual ICollection<tbl_Mjere> tbl_Mjere { get; set; }
        public virtual ICollection<tbl_Naslovi> tbl_Naslovi { get; set; }
        public virtual ICollection<tbl_Natpisi_i_oznake> tbl_Natpisi_i_oznake { get; set; }
        public virtual ICollection<tbl_Nazivi> tbl_Nazivi { get; set; }
        public virtual ICollection<tbl_Ocuvanost> tbl_Ocuvanost { get; set; }
        public virtual ICollection<tbl_Povijest_predmeta> tbl_Povijest_predmeta { get; set; }
        public virtual ICollection<tbl_Pripadnosti> tbl_Pripadnosti { get; set; }
        public virtual ICollection<tbl_Reference> tbl_Reference { get; set; }
        public virtual ICollection<tbl_Sadrzaj> tbl_Sadrzaj { get; set; }
        public virtual ICollection<tbl_U_Dijelovi_predmeta> tbl_U_Dijelovi_predmeta { get; set; }
        public virtual ICollection<tbl_U_Materijali_u_dijelovima> tbl_U_Materijali_u_dijelovima { get; set; }
        public virtual ICollection<tbl_U_Predmeti_na_izlozbama> tbl_U_Predmeti_na_izlozbama { get; set; }
        public virtual ICollection<tbl_Vrijednosti> tbl_Vrijednosti { get; set; }
    }
}
