//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Inventarizacija
    {
        public Nullable<int> ID_Broj { get; set; }
        public Nullable<int> INV_ID_Inventirao { get; set; }
        public string INV_Datum_inventiranja { get; set; }
        public string INV_Napomena { get; set; }
        public string INV_Inventarni_omot { get; set; }
        public string INV_SD { get; set; }
        public Nullable<int> INV_ID_Odgovornost_predmet { get; set; }
        public string INV_Slobodni_tekst { get; set; }
        public int ID { get; set; }
        public Nullable<int> INV_Datum_inventiranja_SORT { get; set; }
        public bool INV_Prijepis { get; set; }
    
        public virtual tbl_Kartica tbl_Kartica { get; set; }
        public virtual tbl_T_Kustosi tbl_T_Kustosi { get; set; }
    }
}
