//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Kartica
    {
        public int ID_Broj { get; set; }
        public string KRT_Inventarni_broj { get; set; }
        public string KRT_SORT_Inv_br { get; set; }
        public string k1 { get; set; }
        public string Zbirka { get; set; }
    }
}
