//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Stuff_ALL
    {
        public int ID_Broj { get; set; }
        public string KRT_Inventarni_broj { get; set; }
        public Nullable<int> KRT_IDT_Zbirka { get; set; }
        public string naslovi { get; set; }
        public string nazivi { get; set; }
        public string Autori { get; set; }
        public string Datacija { get; set; }
        public string Mjesta { get; set; }
        public string zbirka { get; set; }
        public string MC_Staza_slike { get; set; }
        public string KRT_SORT_Inv_br { get; set; }
        public string Mit { get; set; }
        public string Mjere { get; set; }
        public string kataloskaJedinica { get; set; }
        public string teh { get; set; }
        public string Mat { get; set; }
    }
}
