//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Zbirke_prva_zadnja_zbroj
    {
        public Nullable<int> KRT_IDT_Zbirka { get; set; }
        public Nullable<int> zbroj { get; set; }
        public int prvi { get; set; }
        public int zadnji { get; set; }
        public string Pojam { get; set; }
        public Nullable<int> Nad_IDT { get; set; }
    }
}
